This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./book.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file book.acn....done (299 entries accepted, 0 rejected).
Sorting entries.....done (2855 comparisons).
Generating output file book.acr....done (218 lines written, 0 warnings).
Output written in book.acr.
Transcript written in book.alg.
